### ISSUE TITLE
Issue proceeding to deconvolution

### ISSUE THREAD

**Issue by yyolanda** [li-lab-mcgill/gtm-decon#4]
Dear authors,

I have encountered the following issue while running the tutorial code with the binary included in the "gtm_decon_code" folder:
``
Running GTM Deconvolution Pipeline
Writing results to gtm_decon/tutorial_results
**********************************

Saving genes file to ../gtm_decon/tutorial_results/genes.txt ...
Successfully wrote genes file to ../gtm_decon/tutorial_results/genes.txt
Saving meta file to ../gtm_decon/tutorial_results/meta.txt ...
Successfully wrote meta file to ../gtm_decon/tutorial_results/meta.txt
Saving training file to ../gtm_decon/tutorial_results/trainData.txt ...
Successfully wrote training file to ../gtm_decon/tutorial_results/trainData.txt
Saving prior file to ../gtm_decon/tutorial_results/priorData.txt ...
Successfully wrote prior file to ../gtm_decon/tutorial_results/priorData.txt
../gtm_decon/PythonWrapper/GTM_decon.py:583: UserWarning: Duplicate genes found in bulk data indices! Dropping duplicates, keeping first!
  warnings.warn('Duplicate genes found in bulk data indices! Dropping duplicates, keeping first!')
Saving bulk text format file to ../gtm_decon/tutorial_results ...
Successfully wrote bulk file to ../gtm_decon/tutorial_results/bulkData.txt
Saving attributes dict_keys(['experiment_name', 'n_topics', 'engine_path', 'genes', 'celltypes', 'bulk_samples', 'verbose', 'output_intermediates', 'override_geneset']) to path: ../gtm_decon/tutorial_results/GTMParameters.json
Successfully saved GTMWrapper parameters to ../gtm_decon/tutorial_results/GTMParameters.json
Running Inference Engine ...
../keyatm/gtm_decon/gtm-decon-code/gtm-decon: symbol lookup error: ../gtm_decon/gtm-decon-code/gtm-decon: undefined symbol: _ZN4arma23arma_rng_cxx11_instanceE
Completed Running Inference Engine.
../gtm_decon/PythonWrapper/GTM_decon.py:793: UserWarning: No deconvolved results were found in this directory, check if there are any metagene/metagene_normalized files.
  warnings.warn("No deconvolved results were found in this directory, check if there are any metagene/metagene_normalized files.")
Completed running Pipeline.
``

It seems that the binary included in the "gtm_decon_code" folder was built using Armadillo version 8. However, I have tried with Armadillo version 8.200.0, 8.500.0 and 8.600.0 (under different conda environments) but got the same problem shown above. Could you please help with it? 

Thank you very much!

**Comment by aosakwe** [comment]
Hi @yyolanda,
Thank you for using gtm-decon. 

Could you share the output you receive when you run ```make``` in ```/gtm-decon-code```? In addition, I would suggest editing the ```Makefile``` to replace "g++-8" with "g++" if you have not done so already. I tested the model and found it works when re-compiling with Armadillo version 9 or above.

**Comment by yyolanda** [comment]
Thank you @aosakwe for your response! That's very helpful. It solves my problem perfectly!
